# Generated by Django 2.2.5 on 2019-09-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
