# Generated by Django 2.2.5 on 2019-09-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0002_auto_20190918_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='longitude',
        ),
        migrations.AddField(
            model_name='country',
            name='curr_rate',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
