# Generated by Django 2.2.5 on 2019-09-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0003_auto_20190919_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='curr_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
