# Generated by Django 2.2.5 on 2019-09-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0004_auto_20190919_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
    ]
