# Generated by Django 2.2.5 on 2019-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0005_remove_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='curr_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
