# Generated by Django 2.2.5 on 2019-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0006_auto_20190919_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
