# Generated by Django 2.2.5 on 2019-11-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0007_country_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='audio',
        ),
        migrations.AddField(
            model_name='country',
            name='gdp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='num_smokers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IMR_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beat_site.Country')),
            ],
        ),
    ]
