# Generated by Django 2.2.5 on 2019-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0009_auto_20191127_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='IMR_Rate',
        ),
    ]
