# Generated by Django 2.2.5 on 2019-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_site', '0010_auto_20191127_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
